// Code generated by mockery v2.18.0. DO NOT EDIT.

package resolver

import (
	model "github.com/rhzs/gqlgen-todos/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// mockTodoStorage is an autogenerated mock type for the todoStorage type
type mockTodoStorage struct {
	mock.Mock
}

// Load provides a mock function with given fields:
func (_m *mockTodoStorage) Load() []*model.Todo {
	ret := _m.Called()

	var r0 []*model.Todo
	if rf, ok := ret.Get(0).(func() []*model.Todo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Todo)
		}
	}

	return r0
}

// Store provides a mock function with given fields: todo
func (_m *mockTodoStorage) Store(todo *model.Todo) {
	_m.Called(todo)
}

type mockConstructorTestingTnewMockTodoStorage interface {
	mock.TestingT
	Cleanup(func())
}

// newMockTodoStorage creates a new instance of mockTodoStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockTodoStorage(t mockConstructorTestingTnewMockTodoStorage) *mockTodoStorage {
	mock := &mockTodoStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
